# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ./tasio_pro/package.json /app/package.json
RUN npm i npm@6.14.4
RUN npm install
COPY ./tasio_pro/. .
# RUN npm install @vue/cli@3.7.0 -g

# start app
CMD ["npm", "run", "build"]
