# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /app/tasio_pro
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/tasio_pro/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ./tasio_pro/package*.json ./
RUN npm install
COPY ./tasio_pro/. .
RUN npm run build
EXPOSE 9772
#COPY . .
# RUN npm install @vue/cli@3.7.0 -g

# start app
CMD ["npm", "run", "serve"]
